# Generated by Django 4.2.7 on 2026-05-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_categories_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='container',
            field=models.CharField(blank=True, choices=[('glass', 'Стеклянная бутылка'), ('can', 'Жестяная банка'), ('pet', 'ПЭТ')], max_length=10, null=True, verbose_name='Тара'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_alcoholic',
            field=models.BooleanField(default=False, verbose_name='Алкогольный'),
        ),
        migrations.AddField(
            model_name='products',
            name='volume',
            field=models.CharField(blank=True, choices=[('0.25', '0.25 л'), ('0.5', '0.5 л'), ('0.75', '0.75 л'), ('1.0', '1 л'), ('1.5', '1.5 л'), ('2.0', '2 л')], max_length=5, null=True, verbose_name='Объём'),
        ),
    ]
