# Generated by Django 4.2.7 on 2026-06-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Доставляется', 'Доставляется'), ('Выполнен', 'Выполнен'), ('Отменён', 'Отменён')], default='В обработке', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
