# Generated by Django 4.2.7 on 2026-06-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('Кант', 'Кант'), ('Бишкек', 'Бишкек')], default='Кант', max_length=50, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='order',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер дома/квартиры'),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, choices=[('Ленина', 'Ленина'), ('Гагарина', 'Гагарина'), ('Токтогула', 'Токтогула'), ('Фрунзе', 'Фрунзе'), ('Логвиненко', 'Логвиненко'), ('Центральная', 'Центральная'), ('Зубкова', 'Зубкова'), ('Панфилова', 'Панфилова')], max_length=100, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True, verbose_name='Ориентиры / Доп. информация'),
        ),
    ]
